### ISSUE TITLE
[Database Design Report] Submission:  18 Oct 2024 (Fri), 2359

### ISSUE THREAD

**Issue by Novianaghovin** [Novianaghovin/TIC2601#1]
DB report must include:
1. Diagrams
    > ER Diagram (ERD)
    > Relational schema (the below 2 styles are acceptable)
        >> This style: https://i.sstatic.net/9uFmQ.jpg
        >> Or this style: https://i.sstatic.net/miI4Q.pngk
    > Diagrams in report are after normalization

2. Writings should cover:
> Any assumptions made during the design process and in the ERD (ERD see Tutorial 6 Q2 for reference) should be clearly stated and justified.
> There should be a logical explanation for any trade-offs made, such as handling of complex relationships or avoiding normalization in certain cases (Normalization based on today's lecture)

Report grading guidelines:
- The professor will primarily focus on how well our diagram ties back to the business scenario. If anything in the diagram is unclear or needs more detail, the written explanations will be used for clarification (see above point #2)
- It's crucial that our database design aligns with the business context and follows the concepts taught in lectures.
- Note: We can modify the database design after submitting the report in Week 9 without affecting our final report grade.

1. Business Alignment
* Does the design reflect the business scenario accurately? The database should clearly capture all key entities, relationships, and attributes described in the business case.

* Consistency: Is there a logical connection between the design and the real-world requirements? Are the data flows and business rules respected in the structure?

2. Normalization
* Appropriate normalization level: The design should be normalized to eliminate redundancy and ensure data integrity, but avoid over-normalization that makes queries or updates inefficient.
* Handling of exceptions: If certain relations are not normalized, there should be clear justifications explaining the decision based on the context.

3. ER diagram
* Clarity and Correctness of the ERD: The ER diagram should use the correct notations (entities, relationships, cardinalities, etc.) and be easy to read.
* Completeness: All entities, relationships, and attributes relevant to the business scenario should be present.

**Comment by thebunnymama** [comment]
The above grading criteria should not be an 'issue'; I shifted the above into wiki and added the timeline and deliverables too. Recreated new issues to better reflect the task on hand
