### ISSUE TITLE
[Database] Create Entity-Relationship Diagram (ERD)

### ISSUE THREAD

**Issue by thebunnymama** [Novianaghovin/TIC2601#3]
**Task:**
Phase 1: Identify key entities based on project requirements
Phase 2: Define attributes for each entity and identify relationships (e.g., 1:N, M:N).
Phase 3: Map out primary and foreign keys to establish relationships between tables.
Phase 4: Draft a rough version of the ERD using Miro
Phase 5: Share the draft with the team for review, collect feedback, and iterate on the diagram.

**Resources:**
Refer to the [project’s functional specifications](https://github.com/Novianaghovin/TIC2601/wiki/Project-Grading-Criteria) for grading criteria.
Review lecture/ tutorial ERDs for formatting and structure guidelines.

**Acceptance Criteria:**
ERD represents all necessary database entities and their relationships.
The diagram reflects project-specific business rules.

**Deadline: 27 Sep 2024**

**Comment by tacocat-meow** [comment]
Creation of ERD completed on 26/7 and informed in Telegram group chat.

**Comment by thebunnymama** [comment]
Creation of ERD completed on 26/9 and informed in Telegram group chat.

![photo_6316464499804194939_w](https://github.com/user-attachments/assets/3023b6a2-7e04-4f39-874b-aafdc6085785)
